### ISSUE TITLE
Layout Structure (Initial Sections)

### ISSUE THREAD

**Issue by ribeiroevandro** [artesaos/site#1]

**Comment by vinicius73** [comment]
# Seções

## Pacotes

> Nosso pacotes com metadados e links para a documentação

## Sobre

> Uma descrição dos objetivos do nosso grupo  

## Quem somos

> Traz via API uma lista de todos que já contribuiram conosco

### Contribua

> Guia de como contribuir

### Videos

> Videos de Screencasts ou Hangouts

**Comment by vs0uz4** [comment]
### Deem suas opiniões nas opções publicadas

1- Página de Membros
- Listagem de 4 membros ou 3 membros?
- Quais informações pertinentes aos membros colocar?
- Qual a melhor combinação de cores?

**Comment by vinicius73** [comment]
@vs0uz4 acho q a listagem de membros pode ser o mais simples/pequena possível
