### ISSUE TITLE
Layout Proposal Survey

### ISSUE THREAD

**Issue by hernandev** [artesaos/site#20]
List of related issues/PR's with layout proposals
- 1 - Foo
- 2 - Bar

Use a single comment to vote in an option, voting in multiple is **allowed** but you should **never** vote on the same twice.

V1 http://imgur.com/a/OIaJq
V2 http://imgur.com/a/VHybG
V3 http://imgur.com/a/IZjdU
V4 http://imgur.com/a/hLnEs
V5 http://imgur.com/PifsmMP *

**Comment by vinicius73** [comment]
V1 http://imgur.com/a/OIaJq
V2 http://imgur.com/a/VHybG
V3 http://imgur.com/a/IZjdU
V4 http://imgur.com/a/hLnEs
V5 http://imgur.com/PifsmMP *

**Comment by SOSTheBlack** [comment]
V1

**Comment by vluzrmos** [comment]
V2

**Comment by limatheus** [comment]
gostei do v2, mas deixo aqui minha sugestão http://imgur.com/a/HF3va

**Comment by lukzgois** [comment]
V2

**Comment by sergiopeluzzi** [comment]
V1 e V4

**Comment by sergiopeluzzi** [comment]
V4

**Comment by vinicius73** [comment]
V2 mesclado com V3

**Comment by andreoav** [comment]
V2

**Comment by luanrodrigues** [comment]
V2

**Comment by williamoliveira** [comment]
V2, but... with white backgroud in "About Us" page and smaller developers avatars, maybe something like this: http://puu.sh/hSoAs/2a46ede6a2.png

**Comment by ianrodrigues** [comment]
v2

**Comment by stivyw** [comment]
V1 extends v2 implement v5

**Comment by jansenfelipe** [comment]
V2

**Comment by mandado** [comment]
V2
