### ISSUE TITLE
Proposal: Drop that idea!

### ISSUE THREAD

**Issue by vluzrmos** [artesaos/site#27]

**Comment by ribeiroevandro** [comment]
Because that young

**Comment by cbcaio** [comment]
Galera, deem propostas aqui de preferencia antes de abrir issues! Vamos tentar organizar o repo :)
Evitem criar muitos issues para irmos solucionando eles e fechando, assim a galera consegue se encontrar e talvez contribuir mais rapidamente o/ é nois

**Comment by vinicius73** [comment]
Bugs devem ser repostados em issues separadas.
