### ISSUE TITLE
JSON + VueJS

### ISSUE THREAD

**Issue by cbcaio** [artesaos/site#29]
Galera, sobre essa parte podem falar comigo ou com o @icarcal, estaremos enviando tudo para o master do artesaos/site

**Comment by lemesdaniel** [comment]
blz, precisando falem ai.

**Comment by valentimaraujo** [comment]
Eu não manjo de vue.js mas quero acompanha e ajudar nesta parte

**Comment by vs0uz4** [comment]
Galera, para os avatars, na seção de desenvolvedores poderíamos utilizar links do gravatar não acham uma boa?

**Comment by mauri870** [comment]
@vs0uz4 Boa idéia

**Comment by cbcaio** [comment]
Como é que faço para pegar os links do gravatar de cada um ? Estamos com os jsons de jeito e o vue carregando eles já no fork meu e do icaro. Outro detalhe é que precisamos saber os dados de qm vai aparecer como contribuidor la, adicionei os membros atuais do artesaos pelo perfil do github com nome nick, github url e avatar url (ficou faltando).

**Comment by mauri870** [comment]
N consegue fazer uma requisição pra api do github @CbCaio ? N precisa de autenticação nem nd

**Comment by mklemersson** [comment]
Não sei se a galera q ficou com o trabalho do Json fez assim, mas poderiam fazer a requisição na API do GitHub e aproveitar o Json q vem de lá e só completar com os dados q faltam.

**Comment by cbcaio** [comment]
então, mas eu preciso saber os perfis de qm q eu vou precisar fazer a requisição né hahaha

**Comment by mauri870** [comment]
Yep, porém vão ter q contatar a api pra pegar os dados de todos os membros... Isso vai impactar mt no carregamento do site... N sei se é possível fazer isso, mas n tem como contactar a api de vez em quando só pra atualização, e daí manter um json destes dados pra servir o site?

**Comment by cbcaio** [comment]
com o backend podemos fazer isso, mas por agora acho que rola fazer um json só com os links doq for usar, facilita na hora de atualizar tb, na pior das hipoteses pego a url na mão de cada um hahaha

**Comment by icarcal** [comment]
Galera, a gente consegue utilizar os dados da api do github sim, buscando os dados dos membros do artesaos (https://api.github.com/orgs/artesaos/members)
Tudo bem se utilizarmos somente o usuário do github de cada um?
Inclusive, já existe o campo gravar_id @vs0uz4 e também o avartar_url, que é o próprio avatar do github.
O link do branch citado pelo @CbCaio é o https://github.com/icarcal/site/tree/develop.

**Comment by valentimaraujo** [comment]
Só pra tirar uma duvida, o Vinicius mostrou ontem um exemplo de como funcionava o site que ele tinha como referencia que eu esqueci qual é.... lá os contribuintes adicionava seus packages em um json e o site puxava deste json todas as infos. Não era isto ou eu boiei no hangout???/

**Comment by icarcal** [comment]
É isso mesmo @valentimaraujo, criamos o json aqui: https://github.com/icarcal/site/blob/develop/front/artesaos-packages.json

**Comment by valentimaraujo** [comment]
Não seia o caso de add mais um campo com passando a url do avatar?? (S eu estiver falando besteira me falem...!!!)

`{
        "project_name": "Laravel Installer",
        "description": "Install Laravel Framework with any version you want.",
        "url": "https://github.com/artesaos/laravel-installer",
                "avatar": "https://avatars2.githubusercontent.com/u/1561347",
        "laravel_compatible": [
            "4.2",
            "5.0",
            "5.1",
            "5.2"
        ],
        "project_version": "v1.0.0"
    },`

**Comment by mauri870** [comment]
@icarcal Seria bom ter os lideres dos projetos na descrição dos mesmos ;)

**Comment by cbcaio** [comment]
O que ficou decidido é que vamos utilizar a api do github para exibir os membros do artesaos (unica desvantagem vai ser que não vai aparecer o nome completo, só o nick). Já a parte do json ficou só para os packages, que assim temos mais liberdade para colocar a descrição e a compatibilidade. Quem quiser ver como está é só entrar no artesaos/site master que ja estaremos mandando pra la, qualquer contribuição podem mandar um pull request direto pra la que estaremos olhando e dando merge.

Em relação a galera do front end, se alguém ler aqui, por favor façam a mesma coisa, mandem pull requests depois que terminarem para nós integrarmos o vue com o html de vcs :)
vlw galera, to gostando de ver todo mundo se ajudando! estamos uma bagunça nos branchs,forks, prs, etc mas fica de aprendizado para próxima ver nos organizarmos melhor! hahaha

**Comment by vs0uz4** [comment]
Sugiro que sigamos o que foi conversado no Hangout, partir do princípio do mais simples, e depois ir evoluindo as versões do site gradativamente. Se começarmos a querer implementar várias coisas, acrescentar várias coisas, acontecerá o que acontece sempre, a coisa fica parada.

@valentimaraujo o avatar, como é na seção de contribuintes/desenvolvedores e a mesma será alimentada através da api do github, já irá constar essa informação através da propriedade "avatar_url".

@CbCaio exatamente conforme você mencionou.

@icarcal Show, não sabia que na API já vinha o link do gravatar, mais como já constatei que nem todos usam, nem todos tem, melhor mesmo é usarmos somente o "avatar_url".

**Comment by lemesdaniel** [comment]
terminaram?

**Comment by cbcaio** [comment]
creio que sim, pelo menos o q falamos q ia fazer haha
