### ISSUE TITLE
Recursos

### ISSUE THREAD

**Issue by stivyw** [artesaos/site#4]
Galera, vamos discutir quais os recursos vamos utilizar para a implementação do site?

**Comment by vinicius73** [comment]
Opções atuais:

## Lumen + AngularJS

> Vantagem: Poder fazer tratamento de dados complexos e liberar dados limpos na api para o angular, possibilitando o uso externo da API

## AngularJS (puro)

> Mais simples, nao requer um servidor para processar o back-end. Todos os dados serão estáticos

---

É consenso que não devemos usar banco de dados durante pelo menos essa fase inicial, para facilitar a contribuição.

---

@vs0uz Deu inicio ao layout, em breve ele disponibilizara o psd para que todos possam ver e contribuir

**Comment by limatheus** [comment]
Eu acho melhor já começarmos com o Lumen + Angular, mesmo sendo algo estático.
Assim poderemos "escalar" com todas as funcionalidades em mãos, com isso focamos no futuro,

**Comment by stivyw** [comment]
Concordo com o Matheus, poderíamos deixar o Lumen em ponto de ebulição.

**Comment by vluzrmos** [comment]
Concordo com o @matheus-lima também, e lancei um pacote "simple cors" pra usar no lumen https://github.com/vluzrmos/lumen-cors .

**Comment by vs0uz4** [comment]
eu voto por usar o Lumen pelas questões que o @vinicius73 comentou no slack, de podermos consolidar os dados vindos por json.

**Comment by vinicius73** [comment]
Ficou Decidido:
- Lumen
- AngularJS
- Bootstrap
- Less
- GitHub API
